steps:
# This step runs the unit tests on the app
- name: 'python:3.6-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install flask && python test_app.py -v'

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/hello-app:$SHORT_SHA'
  - '-t'
  - 'gcr.io/$PROJECT_ID/hello-app:latest'
  - '.'

# This will pushes the images to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/hello-app:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/hello-app:latest'

